### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by cysin** [Maghoumi/CudaHoG#1]
/usr/local/cuda-7.0/bin/nvcc -I"/root/work/CudaHoG" -I/usr/local/include/ImageMagick-6 -I/usr/include/ImageMagick -I"/root/work/CudaHoG/include" -G -g -lineinfo -O0 --compile --relocatable-device-code=true -gencode arch=compute_20,code=compute_20 -gencode arch=compute_20,code=sm_21 -m64  -x cu -o  "include/codefull/ImageUtils.o" "../include/codefull/ImageUtils.cu" -std=c++11
../include/codefull/ImageUtils.cu(60): error: no instance of overloaded function "codefull::FloatImage::convolve" matches the argument list
            argument types are: (std::vector<Npp32f, std::allocator<Npp32f>>, NppiSize)
            object type is: codefull::FloatImage

../include/codefull/ImageUtils.cu(61): error: no instance of overloaded function "codefull::FloatImage::convolve" matches the argument list
            argument types are: (std::vector<Npp32f, std::allocator<Npp32f>>, NppiSize)
            object type is: codefull::FloatImage

**Comment by Maghoumi** [comment]
You did try to compile using Nsight Eclipse, correct?

**Comment by cysin** [comment]
Yes, I am on CentOS 7 and with CUDA 7 + Nsight Eclipse

**Comment by Maghoumi** [comment]
OK I will look into it and will get back to you.
Sorry about that

**Comment by Maghoumi** [comment]
OK it seems that the latest commit was a bad commit. The issue should be fixed now.
Please check and report back any problems. Thank you for reporting the issue.
